/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("socialAggregator.kotlin-application-conventions")
    id("org.springframework.boot")
    kotlin("plugin.spring")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(11))

    java.sourceSets {
        getByName("main").java.srcDirs("src/main/kotlin")
        getByName("test").java.srcDirs("src/test/kotlin")
    }

}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":core"))


    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
    implementation("org.springframework.boot:spring-boot-starter-web")

    // https://mvnrepository.com/artifact/org.springframework.security/spring-security-core
    implementation("org.springframework.security:spring-security-core")
// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-mail
    implementation("org.springframework.boot:spring-boot-starter-mail")

// https://mvnrepository.com/artifact/com.auth0/java-jwt
    implementation("com.auth0:java-jwt")

    // https://mvnrepository.com/artifact/org.springframework.security/spring-security-config
    implementation("org.springframework.security:spring-security-config")

    // https://mvnrepository.com/artifact/org.springframework.security/spring-security-web
    implementation("org.springframework.security:spring-security-web")



}

application {
    // Define the main class for the application.
    mainClass.set("com.example.socialmediaaggregator.SocialMediaAggregatorApplication")
}

tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootJar> {
    enabled = true
}



