--changelog kpike: created social media token table
CREATE TABLE if not exists social_media_token
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token             VARCHAR(255),
    social_media_type INTEGER,
    app_user          BIGINT,
    CONSTRAINT pk_socialmediatoken PRIMARY KEY (id)
);

ALTER TABLE social_media_token
    ADD CONSTRAINT FK_SOCIALMEDIATOKEN_ON_USER FOREIGN KEY (app_user) REFERENCES app_user (id);
